# Generated by Django 4.0.4 on 2022-05-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging', '0005_alter_ws_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ws',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
